<a href="https://colab.research.google.com/github/M-Ghodrat/Servus/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Why Use NumPy?

- NumPy is short for "Numerical Python".
- It is used for working with arrays.
- It aims to provide an array object that is up to 50x faster than traditional Python lists. It is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [4]:
import numpy

In [5]:
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### Array vs List

In [7]:
arr_list = [1,2,3,4,5]
arr_numpy = numpy.array([1, 2, 3, 4, 5])

print(arr_list * 2)
print(arr_numpy * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [8]:
arr_list = [1,2,3,4,5]

new_arr = []
for i in arr_list:
  new_arr.append(i*2)

new_arr

[2, 4, 6, 8, 10]

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [11]:
print(np.__version__)

2.0.2


In [17]:
print(type(arr))

<class 'numpy.ndarray'>


## 0-D Arrays

In [6]:
arr = np.array(42)
print(arr)

42


## 1-D Arrays

An array that has 0-D arrays as its elements.

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


## 2-D Arrays

An array that has 1-D arrays as its elements.

In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1]
 [4]]


## 3-D Arrays

An array that has 2-D arrays as its elements.

In [25]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [26]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

In [27]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


## Access Array Elements

In [28]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [29]:
print(arr[1])

2


In [30]:
print(arr[2] + arr[3])

7


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [32]:
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [34]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('4th element on 2nd row: ', arr[1, 3])

4th element on 2nd row:  9


In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
arr.shape

(2, 2, 3)

In [38]:
print(arr[1, 0, 1])

8


In [39]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Slicing Arrays

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [45]:
print(arr[4:])

[5 6 7]


In [46]:
print(arr[:4])

[1 2 3 4]


In [48]:
print(arr[-3:-1])

[5 6]


In [49]:
print(arr[1:5:2])

[2 4]


In [50]:
print(arr[::2])

[1 3 5 7]


In [51]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [52]:
print(arr[1, 1:4])

[7 8 9]


In [53]:
print(arr[0:2, 2])

[3 8]


In [54]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Checking the Data Type of an Array

In [56]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [57]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [58]:
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)

float64


In [59]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [60]:
arr = np.array([1, 0, 3])
newarr = arr.astype(str)

print(newarr)
print(newarr.dtype)

['1' '0' '3']
<U21


In [65]:
arr = np.array([1, 0, -3])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## Copy vs View

### Copy:

In [68]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### View:

In [70]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Shape of an Array

In [79]:
arr_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr_2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_1.shape)
print(arr_2.shape)
print(arr_1.ndim)
print(arr_2.ndim)

(2, 4)
(4, 2)
2
2


In [58]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# [[[[[1 2 3 4]]]]]
#  [[[[1 2 3 4]]]]
#   [[[1 2 3 4]]]
#    [[1 2 3 4]]
#     [1 2 3 4]

## Reshaping arrays

In [80]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.shape

(12,)

In [87]:
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [90]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Unknown Dimension

You are allowed to have one "unknown" dimension.

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Note:**  We can not pass -1 to more than one dimension.

### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


**Example:**

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4 5 6 7 8]
1
(8,)


In [84]:
newarr = arr.reshape(1,-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[1 2 3 4 5 6 7 8]]
2
(1, 8)


In [85]:
newarr = arr.reshape(-1,1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
2
(8, 1)


## Iterating Arrays


In [86]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [88]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [89]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [90]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [91]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


## Joining NumPy Arrays

If axis is not explicitly passed, it is taken as 0.

In [110]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [115]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Stacking is same as concatenation, the only difference is that stacking is done along a **new** axis.

In [116]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


## Searching Arrays

In [117]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [118]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7]),)


## Sorting Arrays


In [119]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [120]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [121]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


If you use the `sort()` method on a 2-D array, both arrays will be sorted:

In [122]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtering Arrays

In [124]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [125]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [126]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## Generate Random Number


In [127]:
from numpy import random

x = random.randint(100)
print(x)

44


In [128]:
x = random.rand()
print(x)

0.44279760248298394


In [129]:
x=random.randint(100, size=(5))
print(x)

[20 36 35 87  7]


In [130]:
x = random.randint(100, size=(3, 5))
print(x)

[[80 19 73 66 30]
 [54 36  8 65 43]
 [97 27 90 97 89]]


In [131]:
x = random.rand(5)
print(x)

[0.33089942 0.65621044 0.18794108 0.71011882 0.09092007]


In [132]:
x = random.rand(3, 5)
print(x)

[[0.86974367 0.92977301 0.78420289 0.73441737 0.75343822]
 [0.06921426 0.46398297 0.57074715 0.67828385 0.72102639]
 [0.07392245 0.76575446 0.08393216 0.3728439  0.97719978]]


### Generate Random Number From Array


In [133]:
x = random.choice([3, 5, 7, 9])
print(x)

7


In [134]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 9 3 9 3]
 [9 5 5 9 7]
 [5 5 7 3 5]]


In [136]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 7 7 7 7 7 7 7 7 7 5 3 7 5 5 7 5 7 7 5 5 3 7 7 5 5 3 7 7 5 7 5 7 7 5 7
 5 5 7 5 5 7 5 3 5 3 7 7 7 7 3 3 7 7 5 7 7 7 5 7 7 7 7 7 7 5 5 5 5 7 5 7 7
 5 5 7 5 7 7 7 7 5 5 7 5 3 3 5 7 5 7 7 3 7 7 5 7 7 5]


The sum of all probability numbers should be 1.

## Shuffling Arrays


In [137]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 1 2 3 4]
